# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 767a9d9c65be3ba76bcc82ed0f9c81200bbb082cbb6695088bb5b39ad63268577048a75eda0dae4e89f60ad4391f3c75b0a5e5b6d220e4526e2cb0d1bd2b38b1

test:
  secret_key_base: 21348e0899844304c3cf0c0b76710682771d0bebb021824e944c9b939045f2d2e75554bdf9d0902be392cce05c504aa5c9b5f75935a3bedb86ad58bdbfb5854d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
